### PR TITLE
Feature/#110 incorrect demo path when publishing

### PR DESCRIPTION
**Pull request by danyaljim**

### CODE REVIEW

**Comment by feserafim** [comment]
Hey @danyaljim , any progress about @antgamdia commentary?

By the way, can you implement a new step in your test that checks if the corresponding demo URL path is accessible? 
You can do that by using `TestCase.getStatusCode(url)` and evaluate if the returned status code for the corresponding url path is `200`.

**Comment by danyaljim** [comment]
Hi @feserafim I closed the initial pull requests and made a new one with code changes, actual pull request include this changes. Close comment included thanks to @antgamdia I don´t know why this message doesn't appear now, maybe reopen the pull request deleted it.

**Comment by feserafim** [comment]
@danyaljim I've just seen your changes, but there is no test implementation that verifies this bug won't happen again.
Please, could you implement that as I said in [the previous comment](https://github.com/isa-group/ideas-studio/pull/115#issuecomment-182789136).

Sorry to lengthen your pull request, but it's necessary to have our system working based on integration tests.

Thank you for your comprehension!

**Comment by danyaljim** [comment]
Thanks @feserafim! 
New problems occurred resolving this issue. Now issue and associated bugs are fixed. Tests are also implemented.

**Comment by feserafim** [comment]
There are some conflicts in this pull request. @danyaljim do you mind to take a look at that? It might be because both branches share the same code.
You can solve this by merging develop into your branch.

**Comment by danyaljim** [comment]
Done

**Pull request merged**
